language: ruby
rvm:
- 2.1.2
before_install:
  - gem install bundler -v 1.14.6
script:
- bundle exec rspec
- bundle exec yard stats | grep "100.00% documented"
notifications:
  slack:
    secure: o/+iJrZTKqv+1dRmqCyQRk4RnO/30phrwg6gwR2465fFNOBns+sqwZpFRXBXn9vJSTtw6jRp3/UL60Baj4BNTV/sfBWaPCxRzHC0O1QHh3XlRTkOtolKRUD4htjcnJ7/OvQwGaHFhFp6pW3RNQpZtrjkzmBC5n/efgF89AAlS0MK957nvvg9PTDq/C38MRg/F0bKk23zmyDyHfbPoGl0BvwVaqa48J1KgqTqRY7ve47ShrISwSQPehmuBOKblspf+cvrqAra9CVUnPJCEhnNsI7dzHLcUYiMajzXMEW0Kth7FqUWjxFJ3EMO9nOSEbU1fgWCACVgE8z8kiY1vD+GgpU3tKrqtyp046SvdoXNXVdGHhZ2wNFuUMs2h/5Cu2SLDsta83bw8vpFayplcL7Skf5n0QtNmlzFTSldL1XQ8nkdFbCd7pTObMebMnsr+XU/HIKXqQSjo2GMFFDM8ec8mjVTxmtuPKEDoGM02OxZ/hAiJPQhulnavSe+rtnRPI8BHmWT84ETI6RU7AF+wFv3NDfTz5sZxLzzT9NAQIsnY4CutzK2CIvnaikKwZcdofrRJfmrfkxIDW6zfx8cftynHeUX0wo3k10vt062rUoM5chUhNptmR1CImx4Yq8f8dTF/NNzhWXXV+r/gT2QfZwwj51b+aLiWCOtYa6nVQgfPTA=
    on_success: never
    on_failure: change
